sudo: required
services:
  - docker


before_install:
  - docker build -t artursuszkiewicz/docker-react -f Dockerfile.dev .


sript:
  - docker run -e CI=true artursuszkiewicz/docker-react npm run test -- --coverage
